# Generated by Django 2.1.7 on 2019-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('speed_limit', models.CharField(max_length=200)),
                ('infractions_speed', models.CharField(max_length=200)),
            ],
        ),
    ]
